name: nexacon_sdk
description: A comprehensive Flutter SDK for Nexacon API, providing plug-and-play P2P calling with WebRTC and NX signaling, plus real-time messaging with presence and read receipts.
version: 1.1.0
homepage: https://nexacon-flutter-sdk.readthedocs.io/
repository: https://github.com/nexacon/nexacon-flutter-sdk
issue_tracker: https://github.com/nexacon/nexacon-flutter-sdk/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.0
  flutter_webrtc: ^0.9.48
  web_socket_client: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
